name: Build check (Linux & Windows with pacman using GNU)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux_build_job:
    runs-on: ubuntu-22.04
    name: Build on ubuntu-22.04 (GNU Make)
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools and dependencies
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -y --no-install-recommends cmake make
          sudo apt-get install -q -y libsoapysdr-dev libusb-1.0-0-dev libiio-dev libad9361-dev
      - name: Configure
        run: cmake -G "Unix Makefiles" -B build
      - name: Build
        run: cmake --build build

  windows_build_job:
    runs-on: windows-latest
    name: Build on Windows (MSYS2 pacman with MinGW Makefiles)
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-soapysdr mingw-w64-x86_64-libusb mingw-w64-x86_64-libiio mingw-w64-x86_64-libad9361-iio
          cache: true
          msystem: MINGW64
          path-type: minimal
          pacboy: false
          release: true
          location: RUNNER_TEMP
          platform-check-severity: fatal
      - name: Configure
        shell: msys2 {0}
        run: cmake -G "MinGW Makefiles" -B build
      - name: Build
        shell: msys2 {0}
        run: cmake --build build
